package com.bilicraft.handheld.update

/**
 * 更新公告清洗：从 GitHub Release body 里提取「给玩家看的公告」。
 *
 * 关键认知（决定整体思路）：
 * release.yml 用 generate_release_notes: true，GitHub 会追加一整段开发者向 changelog——
 * 「## What's Changed」+ 逐条 PR/commit（「* xxx by @user in .../pull/12」）+
 * 「## New Contributors」+「**Full Changelog**: https://...」。这些是给开发者看的，
 * 连正文主体都是 PR 标题，靠「逐行去噪」根本救不回来，去掉署名后剩下的还是 commit 列表。
 *
 * 因此这里改用「按边界切割」而非「逐行降噪」：
 *   作者手写的公告只会出现在自动生成段之前 → 只取第一处自动段标记之前的内容当公告。
 *   作者没写手写公告（整段都是机器生成）→ 切完为空，交给 FALLBACK 兜底，绝不展示 changelog。
 *
 * 这样职责清晰：GitHub Release 页保留完整 changelog 给开发者；App 只呈现作者手写的玩家公告。
 * 想改玩家看到的内容，只需在打 tag 的 Release body 顶部写一段话即可，无需改代码。
 *
 * 变换本身无状态、无副作用：切边界 → 逐行清 markdown → 合并空行 → 重组。
 */
object ReleaseNotes {

    /** 玩家向兜底文案：无手写公告时展示。 */
    const val FALLBACK = "本次更新包含若干优化与修复，建议更新到最新版本。"

    /**
     * 从原始 release body 提取玩家公告。
     * 步骤：截取自动生成段之前的手写正文 → 逐行去列表符/PR署名/markdown → 合并空行 → 重组。
     * 无手写正文时返回 FALLBACK。
     */
    fun humanize(raw: String): String {
        if (raw.isBlank()) return FALLBACK
        val cleaned = raw.lineSequence()
            .takeWhile { !isAutoGeneratedMarker(it) }
            .map { it.trim() }
            .map(::stripListMarker)
            .map(::stripPrAttribution)
            .map(::stripMarkdown)
            .map { it.trim() }
            .toList()
            .let(::collapseBlankRuns)
            .joinToString("\n")
            .trim()
        return cleaned.ifBlank { FALLBACK }
    }

    /**
     * 是否为 GitHub 自动生成段的起始标记。命中即视为「玩家公告结束、开发者 changelog 开始」。
     * 标记与仓库语言无关，GitHub 固定输出英文，故只匹配英文标记；容忍 #、* 前缀与粗体包裹。
     */
    private fun isAutoGeneratedMarker(line: String): Boolean {
        val normalized = line.trim()
            .trimStart('#', '*', ' ')
            .removePrefix("**")
            .lowercase()
        return normalized.startsWith("what's changed") ||
            normalized.startsWith("whats changed") ||
            normalized.startsWith("new contributors") ||
            normalized.startsWith("full changelog")
    }

    /** 去掉行首的无序列表符号（-、*、+）。 */
    private fun stripListMarker(line: String): String =
        line.replace(Regex("^[-*+]\\s+"), "")

    /** 去掉 PR 条目里的开发者署名与链接：「xxx by @user in https://.../pull/12」→「xxx」。 */
    private fun stripPrAttribution(line: String): String =
        line.replace(PR_ATTRIBUTION, "").trim()

    /** 去掉常见 markdown 行内标记：粗体/斜体/行内代码/链接语法，保留可读文本。 */
    private fun stripMarkdown(line: String): String =
        line
            .replace(MD_LINK, "$1")          // [文本](url) → 文本
            .replace("`", "")
            .replace("**", "")
            .replace("__", "")
            .replace(Regex("(?<!\\w)[*_](?=\\S)"), "") // 行内斜体起始符，避开普通乘号/下划线单词

    /** 把连续多个空行压成一个，避免清洗后留下大片空白。 */
    private fun collapseBlankRuns(lines: List<String>): List<String> =
        lines.fold(mutableListOf<String>()) { acc, line ->
            if (line.isEmpty() && acc.lastOrNull()?.isEmpty() == true) acc
            else acc.apply { add(line) }
        }

    private val PR_ATTRIBUTION = Regex("\\s*by\\s+@\\S+\\s+in\\s+https?://\\S+", RegexOption.IGNORE_CASE)
    private val MD_LINK = Regex("\\[([^]]+)]\\((?:[^)]+)\\)")
}